name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: "Generate release changelog"
        id: generate-release-changelog
        # Version 2.4 is available, but creates scrambled output
        uses: janheinrichmerker/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyLastTag: "true" # set to false if no tags exist (buggy with only one tag)
          stripHeaders: "true"
          stripGeneratorNotice: "true"

      - name: Extract the VERSION name
        id: get-version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: "Create GitHub release"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: "${{ steps.get-version.outputs.VERSION }}"
          body: "${{ steps.generate-release-changelog.outputs.changelog }}"
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
